### ISSUE TITLE
Combine editor, frequency, and pronunciation

### ISSUE THREAD

**Issue by zyxue** [donkirkby/pinyincushion#10]
Seems ace cannot be used directly with webpack or browserify, need to use [brace](https://github.com/thlorenz/brace#why-not-just-use-ace) instead

**Comment by zyxue** [comment]
simpleeditor uses a customized simple mode for ace editor, http://xkcd.com/simplewriter/ace/src-min/mode-upwriter.js in order to do the highlighting.

**Comment by zyxue** [comment]
It looks Ace only supports highlighting. Inserting <ruby> tags could be difficult. I am looking at an promising alternative solution now, https://facebook.github.io/draft-js/

**Comment by donkirkby** [comment]
I'm not sure whether putting the pinyin in with the editor will be helpful or not. I'm trying to imagine what it would be like to edit Chinese text with the pinyin mixed in. On the other hand, I really like the simplicity of a "one box" interface.

If you can find an easy way to do it with the highlighted Chinese text in one box and the pinyin in a separate box as it is now, that might be a good way to start.

**Comment by zyxue** [comment]
> If you can find an easy way to do it with the highlighted Chinese text in one box and the pinyin in a separate box as it is now, that might be a good way to start.

Pinyin in a separate box? I am not sure what that would be like. I think draftjs is quite promising. Let dig a little deeper.

**Comment by donkirkby** [comment]
I just meant the way we have it now: one box where you type Chinese text and a second box where you display the Chinese text with pinyin. The only change would be to put the frequency colouring on the box where you type. If draftjs looks promising, then carry on.

**Comment by zyxue** [comment]
I have put a prototype with three elements all together at the [draftjs branch](https://github.com/donkirkby/pinyincushion/tree/draftjs). Most of the code in [PinyinCushionEditor.js](https://github.com/donkirkby/pinyincushion/blob/draftjs/src/PinyinCushionEditor.js) are removed. There is also conflicts with the master branch, so I haven't merged them yet. Overall, it looks neat.
- [ ] fix cursor selection. cursor shouldn't go into `<rt>` tags
- [ ] better design

**Comment by donkirkby** [comment]
It looks _way_ simpler that way, nice work! The cursor selection problem also seems to affect the <kbd>home</kbd> and <kbd>end</kbd> keys. Also, I can't override the pronunciation.
It looks promising, though.

**Comment by zyxue** [comment]
Thanks. I am still not sure if I used the right feature for of Draftjs for our purpose. Currently, I am using [Decorators](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#content), but it seems that [Custom Block Components](maybe https://facebook.github.io/draft-js/docs/advanced-topics-block-components.html#content) can also do the job, I am experimenting.

**Comment by zyxue** [comment]
BTW, it's good to know it affects <kbd>home</kbd> and <kbd>end</kbd> keys, I don't have those two keys on my laptop.

**Comment by zyxue** [comment]
It looks that [Custom Block Components](https://facebook.github.io/draft-js/docs/advanced-topics-block-components.html#content) may not be appropriate as it's mainly for [block-like content](https://facebook.github.io/draft-js/docs/advanced-topics-custom-block-render-map.html#draft-default-block-render-map), Ruby text may not fit very well. so will focus on [Decorators](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#content) and try to fix the [selection](https://facebook.github.io/draft-js/docs/api-reference-selection-state.html#content) problem.

**Comment by zyxue** [comment]
Haven't found a solution yet, filed an issue on https://github.com/facebook/draft-js/issues/717

**Comment by zyxue** [comment]
Will put Pinyin in the display for now.

**Comment by donkirkby** [comment]
I tried out the version on the colorbg branch, and it looks nice. Here are a couple of suggestions before we close this issue:
- [x] There's a bug: the display is one key stroke behind. That often happens when you trigger on the wrong key event. I haven't checked which event you're using.
- [x] Remove the colour from the display on the right, I don't think we need it in both places.
- [x] Merge into master branch.

**Comment by zyxue** [comment]
Hi @donkirkby, I have fixed the two problem, you could take a look and see if it's good to merge now.

**Comment by donkirkby** [comment]
Looks great, merge that baby!
