### ISSUE TITLE
Move from Heroku to GitHub pages

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/pinyincushion#11]
Since we decided not to store anything on the server, we're not really benefiting from Heroku. We could deploy to GitHub pages using pure Javascript instead.
- [x] create a `github-pages` branch, and set it up with a template
- [x] make sure it works on the branch
- [x] create a `docs` folder, and deploy to that
- [x] document deployment in README
- [x] put a redirect page in the main folder that will redirect from Heroku to the new version on GitHub, then push that to Heroku
- [x] remove any old Heroku code and the `github-pages` branch

**Comment by zyxue** [comment]
Why is JS preferred? I thought JSX is encouraged.

**Comment by zyxue** [comment]
I feel github.io can be difficult to debug, isn't it? Heroku is more mature a platform for web apps, no?

**Comment by donkirkby** [comment]
JSX is easier to write than JS, but it requires a server to parse the JSX and convert it to JS that gets sent to the browser. If we write it as JS, then it can be served as static files. As for debugging, I think it will be less confusing to debug Javascript in your browser than to debug the JSX in node.js _and_ debug the resulting Javascript in your browser. Deployment is the same for both: a git commit. One other advantage for JS: Javascript editors like Eclipse and analysis tools like JsHint don't get confused by the HTML elements mixed in with the Javascript.

**Comment by zyxue** [comment]
I thought writing react component in js is quite [verbose](https://facebook.github.io/react/docs/jsx-in-depth.html). Afterall, everything is transformed and bundled together to serve the user, the JSX => JS conversion only happens during development, doesn't it? I use Emacs myself. I thought Eclipse properly has a plugin for JSX. create-react-app already has already had ESLint in package for linting, isn't that good enough instead of JSHint? I haven't read the [difference](https://www.google.ca/search?q=compare+eslint+jslint+jshint&oq=compare+eslint+jslint+jshint&aqs=chrome..69i57.6695j0j7&sourceid=chrome&ie=UTF-8) among ESLint, JSLint, JSHint yet.

**Comment by donkirkby** [comment]
Yes, writing React in JS is more verbose, it's a lot like jQuery. You can probably convert JSX to JS before deployment, but then you need to install npm and a bunch of packages before you can contribute to the project, plus deployment requires more steps than just editing Javascript and pushing to GitHub.

I like JSX, and I would totally use it if there were some server-side processing involved. However, because we ended up doing everything in the browser, I suggest we simplify the technology stack and just use pure Javascript plus ReactJS. Perhaps I'm biased because of my jQuery experience, but the extra code doesn't bother me, and I find it easier to understand what's happening when we don't mix another syntax in with the Javascript.

**Comment by zyxue** [comment]
I think it's all right to try. But I myself don't think trying to simplify the framework/workflow is a good idea given it's already quite nice and clean. For example, you will need draftjs, and you will probably need other js packages in the future. With npm, installation is easy. Without npm, it doesn't feel as extensible. With the experience of create-react-app, I think it's much more elegant to import instead of adding `<script>` tags to the html. Also, import is enabled by webpack + Babel rather than ReactJS itself. Babel takes care of transpiling ES6 to ES5, and webpack takes care of figuring out all the dependencies. It's also recommended to use ES6 now.

**Comment by donkirkby** [comment]
OK, I'll try it out on a branch, and then we can compare to see what the difference is.

**Comment by donkirkby** [comment]
I‘ve made some good progress on the `gh-pages` branch. You can see how it looks at [donkirkby.github.io/pinyincushion](https://donkirkby.github.io/pinyincushion/). I haven't converted the local storage feature yet, and there's a bug if you paste in a big chunk of text, but the basics are working. One helpful thing I found was to make the Javascript less verbose by creating a shortcut:

`e = React.createElement;`

I think this will also be helpful for issue #13, because it will be easier to wrap our pinyin display around some markdown text from the GitHub repository when the pinyin display is all in plain, static Javascript files.

**Comment by zyxue** [comment]
Hi @donkirkby, it looks cool, nice work. But are you sure you want to go that way? I have a few concerns and I am interested in understanding your solutions to them.
1. Given that your js modules are all included via `<script>` tag, how do you manage namespaces, or scopes?
2. Do you have hot reloader?
3. I didn't see Draft.js is imported. Did you extracted `EditorRoot` out of Draft.js?
4. Such a short global variable name like `e`, is it really a good engineering practice?

Honestly, I am really not sure it's that's a the right way to go. I actually like the current setup of development quite a bit. It's very automatic so we could focus on building features and testing them. I like npm & ES6, esp. the module system. The module system feels quite like that of Python. JSX is just syntatic sugar, it's a minor point. If you don't like npm, there is a new package manager called [yarn](https://code.facebook.com/posts/1840075619545360), which intends to address shortcomings of npm. But as npm is the one chosen to create-react-app, I think it's totally fine for now.

**Comment by donkirkby** [comment]
Here are my thoughts on those questions:
1. There are a couple of ways to have namespaces in plain Javascript. For simple things, the style I used in [`charLookup.js`](https://github.com/donkirkby/pinyincushion/blob/fb39383af530e664fc77720cd16f5ff3ededb450/javascripts/charLookup.js). For more sophisticated modules with private scope and extensions, I've used a [strange function technique](http://stackoverflow.com/a/5947280/4794) on another [project](https://github.com/cfe-lab/Kive/blob/v0.8.5/kive/portal/static/portal/permissions.js). It looks weird, but it protects your code from changes to the global scope.
2. I do not have a hot reloader, and I don't know if it's possible for plain Javascript. However, our app has so little state that I don't see a big benefit to hot reloading.
3. I recreated a simple version of syntax highlighting in plain Javascript. I couldn't find Draft.js or its equivalent in plain Javascript.
4. When you have a core feature that you call everywhere, it can be a reasonable convention to give it a simple name. For example, the `$` variable in jQuery. I got the idea from the [React docs](https://facebook.github.io/react/docs/react-without-jsx.html), so it seems reasonable.

I don't hate npm, and I'm glad you showed it to me. If we were going to include a server-side component to the app, then I would certainly use npm to manage the whole project and write everything in ES6/JSX. However, we're running everything in the browser, so I'd like to keep it simple with plain Javascript. This version has no deployment step, it gets served directly from the git repo. The plain Javascript will also make it more approachable for other developers, they don't need to know ES6.

**Comment by zyxue** [comment]
I see. You have some valid points. But I thought the app is only simple for the current. We don't know when it would become useful to add a server side stuff to it or have a more complicated state on the browser side. Keeping the practice in an extensible (or scalable) way sounds a good idea to me. I thought more React developers who wants to contrinbute would be more familiar with JSX than the javascript way because facebook is encouraging it, but I don't have any numbers to support that :P.

**Comment by zyxue** [comment]
I am very impressed that you implemented the draft.js like editor from  scratch. There is a small bug though, sometimes the text doesn't get highlighted right away when I start typing, e.g. 

![screen shot](https://ibin.co/w800/30NdpgNnBYaB.png)

**Comment by donkirkby** [comment]
Can you think of any features you want to add that would involve the server? My rough plan is to get it to the point where people can edit text and contribute articles through GitHub pull requests, then stop adding features and just work on simplifying articles from places like Wikipedia and [Global Voices](https://zhs.globalvoices.org/).

Another advantage to a static site is that we could take article contributions from pull requests, and merge them on GitHub using only the browser. There's no extra deployment step.

I don't know which is more popular, plain Javascript or JSX, but this [Reddit discussion](https://www.reddit.com/r/javascript/comments/2cknh2/react_js_jsx_vs_js/) seems evenly split. My personal experience is with plain Javascript, so that's why I'm hesitant to take on JSX.

As for the bug you found, I haven't been able to reproduce it. Can you post a new issue with the steps to reproduce, please? Include the browser and operating system.

**Comment by donkirkby** [comment]
Thanks for all the discussion. You've convinced me to reconsider this plan, so I'm going to look at other options for deploying a static web site. This list of [complementary tools](https://github.com/facebook/react/wiki/Complementary-Tools) includes a couple for that purpose. Another option is to include Babel and an ES6 shim as support scripts to run in the browser as in this [example](https://github.com/facebook/draft-js/blob/master/examples/color/color.html). I think the launch speed will be faster with the first option.

**Comment by zyxue** [comment]
Hey Don, Sorry. I've been a bit busy with my research project in the past a couple of weeks, so I haven't thought carefully about your last comment yet. What convinced you to reconsider github.io though, what's the biggest problem as you see it now?

**Comment by donkirkby** [comment]
The two reasons I prefer GitHub pages over Heroku for this project:
1. Loading speed - I think Heroku hibernates an app when it's idle.
2. One less dependency - we don't need a Heroku account to deploy to GitHub pages. You can see everything in the repository when you use GitHub pages.

**Comment by zyxue** [comment]
I meant what problems you see for github.io?

**Comment by donkirkby** [comment]
I still want to deploy on github.io (GitHub pages), but these other tools let us write our code using the JSX/ES6 style.

**Comment by zyxue** [comment]
Another idea could be you only push everything in the `build` directory generated by `npm build` to github.io repo while keep all source code in another repo. It's like separate the source code and built one, and only use the built one for github.io. The workflow I could think of can be
1. you have repo for all the source code and people can fork and send pull request, and merge, etc.
2. But when deploying, you run `npm build` and push the build code to another repo under `github.io` domain name.

In this way, you can keep all the current good practice from [create-react-app](https://github.com/facebookincubator/create-react-app) and just create an additional repo for deployment, and work around the two problems you mentioned with heroku.

**Comment by donkirkby** [comment]
Yes, that's one of the options I'm looking at, except it doesn't have to be a separate repository. You can serve GitHub pages from the `/docs` folder of your repository.

**Comment by zyxue** [comment]
Oh, if everything can be in one repo, that's even better!

**Comment by zyxue** [comment]
> My rough plan is to get it to the point where people can edit text and contribute articles through GitHub pull requests, then stop adding features and just work on simplifying articles from places like Wikipedia and Global Voices.

I like this plan, and I feel I can already see why it can be very useful. If we could create a news site/wiki with Pinyin added, that would be hugely helpful to people who are still at the beginning stage of learning Chinese. It sounds awesome, and I would love to discuss more about this.

**Comment by donkirkby** [comment]
OK, I got it to work with the `gh-pages` package. To deploy a new version of the web site, run `npm run deploy`.

It's still on the `gh-pages` branch, so I'm going to see if I can get the `build` script to write to the `docs` folder instead of the `build` folder. I might have to use the `eject` command.

**Comment by donkirkby** [comment]
OK, here's what I have working: just run `npm run build`, and it will generate a new version of the static web site in the `docs` folder. Push that to the GitHub repo, and the new version will appear at [donkirkby.github.io/pinyincushion][gh].

If you have time, please try making a small change and deploying it. Let me know if it works for you.

[gh]: https://donkirkby.github.io/pinyincushion/

**Comment by zyxue** [comment]
Great work, Don! It works, I just tested it by updating the greeting message.
