### ISSUE TITLE
Missing pronunciation for 旁

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/pinyincushion#15]
This character shows up in the frequency list, and `\u65c1` shows up in the `cedict.script` file, but not as a single character. Handle the scenario where pronunciation is only listed for the character as part of a word.

**Comment by zyxue** [comment]
I don't quite understand the question. The pronunciation of 旁, páng, looks fine to me on https://pinyin-cushion.herokuapp.com/

**Comment by donkirkby** [comment]
It looks fine to me too, now. Either I was confused by the light background colour, or it was caused by some other bug. Closing as invalid.

**Comment by zyxue** [comment]
:)
