### ISSUE TITLE
Backup text to local storage

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/pinyincushion#3]
~~Add a permalink button that puts the text into the URL. Maybe a link to tinyurl.com?~~

Store backup of the text to the browser's local storage, so it isn't lost in a crash.

**Comment by zyxue** [comment]
This site does what you like, not sure how the url is generated yet, http://splasho.com/upgoer5/

**Comment by donkirkby** [comment]
That's not quite what I was thinking of, it seems to be more like tinyurl.com.

However, you're right to question how useful it is to read the text from the URL. I'm going to think about whether that would ever be useful, and change this issue to store draft versions of the text in the browser's local storage. That would protect users against losing their work from a crash.
