### ISSUE TITLE
Override pronunciation

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/pinyincushion#5]
We'll store one pronunciation for each character, but some characters have more than one. Let the user specify the pronunciation like this:

```
我得{dei3}去。
```

**Comment by zyxue** [comment]
Some of the pronunciation is capitalized, e.g. `"力":"Li4"`, which may not be necessary.

**Comment by donkirkby** [comment]
Don't know why they have some capitalized, @zyxue. I'll just convert everything to lower case as part of #1.
