### ISSUE TITLE
Preserve whitespace characters in display

### ISSUE THREAD

**Issue by zyxue** [donkirkby/pinyincushion#7]
Currently the whitespace characters (e.g. newline) are stripped for some reason.

**Comment by donkirkby** [comment]
HTML ignores whitespace. We have to use `<p>` or `<br>` or something like that. Before we go down that road, however, we should look at options for using markdown. If we can do markdown with a preprocessing or postprocessing step for adding the ruby text, I think that would be best.

**Comment by zyxue** [comment]
It's currently done simply by

```
            if (char === ' ') {
                html += '&nbsp;';
            } else if (char === '\n') {
                html += '<br>';
            } else { ... }
```

See [here](https://github.com/donkirkby/pinyincushion/blob/master/src/PinyinCushionEditor.js#L56)
